# Site
name: "mytraffic tech & product blog"
title: "mytraffic tech & product blog"
description: "A collection of tech & product ideas from mytraffic"
logo: '/assets/images/logo.png'
favicon: '/assets/images/favicon.ico'
url: 'https://www.mytraffic.io'
baseurl: 'en/tech-post'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sdiemer:
    name: sdiemer
    display_name: SÃ©bastien Diemer
    avatar: '/assets/images/sdiemer.jpg'
    email: sdiemer@mytraffic.fr
    twitter: https://twitter.com/sebdiem
    description: "CTO at mytraffic since 2019"
  awendlinger:
    name: awendlinger
    display_name: 'Antoine Wendlinger'
    email: awendlinger@mytraffic.fr
    avatar: '/assets/images/awendlinger.png'
    description: |
      Data Engineering lead at MyTraffic.
      I love good code, good food, and nitpicking about naming :)


# Plugins (should be available with github pages => https://pages.github.com/versions/)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    formatter: Rouge::Formatters::HTMLLineTable
    block:
    default_lang: python

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, Dockerfile, docker-compose.yml]
